// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl_x-G7ccmAJjJdTnj9qwjZK_XPH1iYk0',
    appId: '1:893073670200:web:9edee9927d125c5f4e26cd',
    messagingSenderId: '893073670200',
    projectId: 'chat-app-2c229',
    authDomain: 'chat-app-2c229.firebaseapp.com',
    storageBucket: 'chat-app-2c229.appspot.com',
    measurementId: 'G-DTEBZLKT90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL9kj-AGVJxopyhz7niayOa4CyL0mt5JQ',
    appId: '1:893073670200:android:9db9bddadc030ec04e26cd',
    messagingSenderId: '893073670200',
    projectId: 'chat-app-2c229',
    storageBucket: 'chat-app-2c229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0nsBAqAxTaXcUXEpuPnPRjtKIwpXuks',
    appId: '1:893073670200:ios:27af3bd029b08dc44e26cd',
    messagingSenderId: '893073670200',
    projectId: 'chat-app-2c229',
    storageBucket: 'chat-app-2c229.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx0nsBAqAxTaXcUXEpuPnPRjtKIwpXuks',
    appId: '1:893073670200:ios:e776a08a4885ecaf4e26cd',
    messagingSenderId: '893073670200',
    projectId: 'chat-app-2c229',
    storageBucket: 'chat-app-2c229.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
